<br />
<p>
    <?php

//    $states = array(1 => 'Active', 0 => 'Inactive');
//    $output = array();

//    $routeParams = array(
//        'controller' => $params['matched']['controller'],
//        'action' => $params['matched']['action'],
//        'role' => $params['matched']['role']
//    );

//    foreach($states as $key => $state):
//        $routeParams['state'] = $key;
//        $output[] = '<a href="' . $this->url($matchedRouteName, $routeParams) . '">' . $state . '</a>';

//        $output[] = '<a href="#">' . $state . '</a>';
//    endforeach;

//    printf($this->translate('Status: %s'), implode(' | ', $output));

    echo '<input type="checkbox">' . $this->translate('Show inactive') . '<br>';

    ?>
</p>