<?php
    $modalName = $this->action;
    if ($this->name) {
        $modalName = $this->name;
    }
?>

<div class="modal hide fade" role="dialog" id="confirm-<?php echo $modalName ?>-modal">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>

        <h3><?php echo $this->title ?></h3>
    </div>
    <div class="modal-body">
        <p><?php echo $this->message ?></p>

        <p><?php echo $this->translate('Do you want to proceed?') ?></p>
    </div>
    <div class="modal-footer">
        <form action="<?php echo $this->application()->url(array(
            'controller' => $this->controller,
            'action' => $this->action
        ));
        ?>" method="post">

            <input id="confirm-<?php echo $modalName ?>-id-value" type="hidden" name="id"/>
            <button type="submit" class="btn btn-danger"><?php echo $this->translate('Yes') ?></button>
            <a class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate('No') ?></a>
        </form>
    </div>
</div>

<?php
$this->inlineScript()
    ->appendScript('
        $(document).ready(function() {
            $("button[data-action=\'confirm-' . $modalName .'\']").click(function(event) {
                id = $(this).attr("data-id");
                $("#confirm-' . $modalName .'-id-value").val(id);
                $("#confirm-' . $modalName .'-modal").modal("show");
            });
        });
        ', 'text/javascript', array('noescape' => true))
?>