<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Acl\Module'                            => __DIR__ . '/Module.php',
  'Acl\Entity\AbstractEntity'             => __DIR__ . '/src/Acl/Entity/AbstractEntity.php',
  'Acl\Entity\AclEntity'                  => __DIR__ . '/src/Acl/Entity/AclEntity.php',
  'Acl\Factory\AclEntityManagerFactory'   => __DIR__ . '/src/Acl/Factory/AclEntityManagerFactory.php',
  'Acl\Listener\Listener'                 => __DIR__ . '/src/Acl/Listener/Listener.php',
  'Acl\ORM\AclEntityManager'              => __DIR__ . '/src/Acl/ORM/AclEntityManager.php',
  'Acl\Repository\EntityRepository'       => __DIR__ . '/src/Acl/Repository/EntityRepository.php',
  'Acl\Service\AbstractService'           => __DIR__ . '/src/Acl/Service/AbstractService.php',
  'AclTest\BaseSetUp'                     => __DIR__ . '/test/AclTest/BaseSetUp.php',
  'AclTest\MockUtil\ServiceManagerMocker' => __DIR__ . '/test/AclTest/MockUtil/ServiceManagerMocker.php',
  'AclTest\Service\AclServiceTest'        => __DIR__ . '/test/AclTest/Service/AclServiceTest.php',
  'AclTest\Bootstrap'                     => __DIR__ . '/test/Bootstrap.php',
);
