<?php
use Equipment\Entity\EquipmentTaxonomyTemplateTypes;

$title = $restraintDocumentation->getTitle($this->translate('on'));
$this->headTitle($title);
$this->layout()->title = $title;
?>
<?php if ($restraintDocumentation->getIllustrationImage()): ?>
        <img src="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getIllustrationImage() ?>" /></p>
<?php endif ?>

<dl class="dl-horizontal">
    <dt><?php echo $this->translate('Load') ?></dt>
    <dd><?php echo $loadDocumentation->getBasicInformation()->getApprovedName() ?></dd>
    <dt><?php echo $this->translate('Load NATO #') ?></dt>
    <dd><?php echo $loadDocumentation->getEquipment()->getFormattedNsn() ?></dd>
    <dt><?php echo $this->translate('Carrier') ?></dt>
    <dd><?php echo $carrierDocumentation->getBasicInformation()->getApprovedName() ?></dd>
    <dt><?php echo $this->translate('Carrier NATO #') ?></dt>
    <dd><?php echo $carrierDocumentation->getEquipment()->getFormattedNsn() ?></dd>
    <dt>
        <?php echo $this->translate('The same certification') ?><br>
        <?php echo $this->translate('is valid for') ?>
    </dt>
    <dd><br><?php echo $restraintDocumentation->getOtherLoads() ?></dd>
</dl>
<hr>
<dl class="dl-horizontal">
    <dt><?php echo $this->translate('Approved for') ?></dt>
    <?php $approvedFormsOfTransportationString = "" ?>
    <?php foreach ($restraintDocumentation->getApprovedFormsOfTransportation() as $approvedTransportation): ?>
        <?php $approvedFormsOfTransportationString .= $approvedTransportation . ', ' ?>
    <?php endforeach; ?>
    <dd><?php echo rtrim($approvedFormsOfTransportationString, ', ') ?></dd>
</dl>
<hr>
<dl class="dl-horizontal">
    <p>
        <?php echo $this->translate('This documentation has been created in accordance with guidelines given by FLO.') ?><br>
    </p>
    <dt><?php echo $this->translate('Elaborated by') ?></dt>
    <dd><?php echo $restraintDocumentation->getCreatedBy() ?></dd>
    <dt><?php echo $this->translate('Approved by') ?></dt>
    <dd><?php echo $restraintDocumentation->getApprovedBy() ?></dd>
    <dt><?php echo $this->translate('Date') ?></dt>
    <dd><?php echo $this->dateFormat($restraintDocumentation->getApprovedDate(), IntlDateFormatter::SHORT) ?></dd>
</dl>
<hr>
<h5><?php echo $this->translate('Important prerequisites'); ?></h5>
<?php echo nl2br($restraintDocumentation->getPrerequisites()) ?>
<hr>
<div class="accordion" id="accordion1">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse3">
                <i class="icon-chevron-down"></i>
                <?php echo $this->translate('Documentation'); ?>
            </a>
        </div>
        <div id="collapse3" class="accordion-body collapse">
            <div class="accordion-inner">
                <?php
                $columns = array(
                    'description' => array(
                        'label' => $this->translate('Description')
                    ),
                    'file' => array(
                        'label' => $this->translate('File'),
                        'callback' => function($file, $view, $attachment) {
                            $formattedValue = "<a class='btn btn-mini' data-rel='open-attachment' data-extension='".$attachment->getExtension() ."' title='" . $attachment->getDescription() . "' href='/content/ladoc-restraint-certified/" . $file . "'><i class='icon-file'></i></a>";
                            return $formattedValue;
                        }
                    ));
                echo $this->bootstrapDataTable($restraintDocumentation->getAttachments(), array(
                    'object_id' => 'pointAttachmentId',
                    'actions' => array(),
                    'search' => false,
                    'columns' => $columns,
                    'table_class' => 'table table-striped ladoc-documentation-attachment-table',
                    'params' => array(
                        'basic' => array('application', 'controller', 'action')
                    )
                ));
                ?>
            </div>
        </div>
    </div>
</div>

<hr>
<?php if ($restraintDocumentation->getImage()): ?>
        <p>
            <?php if (($this->templateType == EquipmentTaxonomyTemplateTypes::COUNTRY_ROAD || $this->templateType == EquipmentTaxonomyTemplateTypes::NAVAL_CRAFT) && $restraintDocumentation->getImageInformation()): ?>
                <a class="custom-tooltip" title="<?php echo $this->translate('Read more') ?>" target="_blank" href="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getImageInformation() ?>">
                    <img  src="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getImage() ?>" />
                </a>
            <?php elseif ($this->templateType == EquipmentTaxonomyTemplateTypes::RAILWAY && $restraintDocumentation->getRailwayCertificate()): ?>
                <a class="custom-tooltip" title="<?php echo $this->translate('Read more') ?>" target="_blank" href="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getRailwayCertificate() ?>">
                    <img  src="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getImage() ?>" />
                </a>
            <?php else: ?>
                <img src="/content/ladoc-restraint-certified/<?php echo $restraintDocumentation->getImage() ?>" />
            <?php endif; ?>
        </p>
<?php endif ?>

