<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Training\Module'                                                  => __DIR__ . '/Module.php',
  'Training\Controller\TrainingController'                           => __DIR__ . '/src/Training/Controller/TrainingController.php',
  'Training\Controller\TrainingSectionAttachmentController'          => __DIR__ . '/src/Training/Controller/TrainingSectionAttachmentController.php',
  'Training\Controller\TrainingSectionController'                    => __DIR__ . '/src/Training/Controller/TrainingSectionController.php',
  'Training\Entity\TrainingSection'                                  => __DIR__ . '/src/Training/Entity/TrainingSection.php',
  'Training\Entity\TrainingSectionAttachment'                        => __DIR__ . '/src/Training/Entity/TrainingSectionAttachment.php',
  'Training\Factory\Service\TrainingSectionAttachmentServiceFactory' => __DIR__ . '/src/Training/Factory/Service/TrainingSectionAttachmentServiceFactory.php',
  'Training\Factory\Service\TrainingSectionServiceFactory'           => __DIR__ . '/src/Training/Factory/Service/TrainingSectionServiceFactory.php',
  'Training\Repository\TrainingSectionRepository'                    => __DIR__ . '/src/Training/Repository/TrainingSectionRepository.php',
  'TrainingTest\Bootstrap'                                           => __DIR__ . '/test/Bootstrap.php',
  'EquipmentTest\BaseSetUp'                                          => __DIR__ . '/test/TrainingTest/BaseSetUp.php',
  'EquipmentTest\MockUtil\ServiceManagerMocker'                      => __DIR__ . '/test/TrainingTest/MockUtil/ServiceManagerMocker.php',
);
