<?php
use LadocDocumentation\Entity\LadocDocumentation;
use Zend\View\Model\ViewModel;

$title = $this->translate('Section') . ' 3/5: ' . $this->title;
$this->headTitle($title);
$this->layout()->title = $title;

$descriptionForm = $this->layout()->getVariable('descriptionForm');
if ($descriptionForm)
    echo $descriptionForm;
?>

<hr/>

<div class="row row-desktop">
    <div class="span12">
        <?php
        echo $this->bootstrapDataTable($points, array(
            'object_id' => 'lashingPointId',
            'actions' => array(
                'add' => array(
                    'label' => $this->translate('Add new'),
                    'attributes' => array(
                        'href' => $this->application()->url(
                            array(
                                'controller' => 'carrier-lashing-point',
                                'action' => 'add',
                                'documentation_id' => $this->documentationId
                            )
                        )
                    )
                ),
                'options' => array(
                    'edit' => true,
                    'delete' => true
                )
            ),
            'table_class' => 'table table-striped',
            'search' => false,
            'columns' => array(
                'placement' => array(
                    'label' => $this->translate('Placement')
                ),
                'description' => array(
                    'label' => $this->translate('Description')
                ),
                'quantity' => array(
                    'label' => $this->translate('Count')
                ),
                'ruptureStrength' => array(
                    'label' => $this->translate('Rupture Strength daN')
                ),
                'lc' => array(
                    'label' => $this->translate('LC daN')
                ),
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            )
        ));
        ?>
    </div>
</div>

<div class="row-fluid">
        <?php echo $this->partial('ladoc-documentation/partial/previous-next-link-buttons.phtml',
            $this->buttonConfig); ?>
</div>

<?php
$this->inlineScript()
    ->appendFile($this->basePath() . '/includes/tinymce/js/tinymce/tinymce.min.js')
    ->appendFile($this->basePath() . '/js/ladoc-documentation/richtext.js');