<?php
$title = $this->translate('Roles');

$this->headTitle($title);
$this->layout()->title = $title;
?>

<div class="row row-desktop">
    <div class="span3">
        <?php echo $this->partial('partial/admin-menu.phtml', 'application') ?>
    </div>
    <div class="span9">
        <?php
        echo $this->bootstrapDataTable($roles, array(
            'object_id' => 'roleId',
            'actions' => array(
                'add' => true,
                'options' => array(
                    'edit' => true,
                    'delete' => array(
                        'icon' => 'trash',
                        'label' => $this->translate('Delete'),
                        'attributes' => array(
                            'data-rel' => 'delete',
                            'data-delete-settings' => json_encode(array(
                                'source' => '<p>' . $this->translate('All the users with the selected role will be moved to the default role, are you sure you want to delete this element?') . '</p>'
                            )),
                            'href' => $this->application()->url(array('controller' => 'role', 'action' => 'delete', 'id' => ':roleId'))
                        )
                    ),
                )
            ),
            'table_class' => 'table table-striped data-table-net',
            'search' => false,
            'columns' => array(
                'name' => array(
                    'label' => $this->translate('Role')
                ),
                'parent' => array(
                    'label' => $this->translate('Parent')
                )
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            )
        ));
        ?>
    </div>
</div>