<?php
$this->headTitle($title);
$this->layout()->title = $title;
$this->inlineScript()->appendFile($this->basePath() . '/js/user.js', 'text/javascript');
?>
<?php  
echo $this->bootstrapForm($form);

?>
<!-- Confirm Cancel Modal -->
<div class="modal hide fade" role="dialog" id="confirm-cancel">
    <div class="modal-header"> 
        <a class="close" data-dismiss="modal">&times;</a>
        <h3><?php echo $this->translate('Cancel') ?></h3>
    </div>
    <div class="modal-body">
        <p><?php echo $this->translate('You are leaving this page, are you sure?') ?></p>
    </div>
    <div class="modal-footer"> 
        <a id="confirm-cancel-btn" class="btn btn-danger" href="<?php echo $this->escapeHtml($this->basePath()) . $cancelRedirect?>">
            <?php echo $this->translate('Yes') ?>
        </a> 
        <a class="btn btn-primary" data-dismiss="modal">
            <?php echo $this->translate('No') ?>
        </a> 
    </div>
</div>
<?php 
$cancelButton = '<button type="button" id="user-btn-cancel" class="btn">' . $this->translate('Cancel') . '</button>';
$this->inlineScript()->captureStart(); 
?>
$(document).ready(function(){
    $("#user-btn-submit").parent().append('<?php echo $cancelButton ?>');
    $("#application_id").removeAttr("required");
});
<?php
$this->inlineScript()->captureEnd();
?>