<?php
$this->headTitle($title);
$this->layout()->title = $title;
$this->inlineScript()->appendFile($this->basePath() . '/js/location.js', 'text/javascript');

$locationResource = 'Application\Entity\LocationTaxonomy';
$canCreateLocation = $this->isAllowed($locationResource, 'create');
$canUpdateLocation = $this->isAllowed($locationResource, 'update');
$canDeleteLocation = $this->isAllowed($locationResource, 'delete');

$actions = array();
$options = array();
if($canCreateLocation)
    $actions['add'] = true;
if($canUpdateLocation)
    $options['edit'] = true;
if($canDeleteLocation) {
    $options['delete'] = true;
    $actions['group'] = array('delete-selected' => true);
}
$actions['options'] = $options;
?>
<!-- Alert -->
<div class="delete-alert alert fade in">
    <button type="button" class="close">&times;</button>    
    <strong><?php echo $this->translate('You must select a Location') ?></strong>
</div>

<div class="row row-desktop">
    <div class="span3">
        <?php echo $this->partial('partial/admin-menu.phtml', 'application') ?>
    </div>
    <div class="span9">        
        <?php
        echo $this->bootstrapDataTable($locations, array(
            'object_id' => 'locationTaxonomyId',
            'table_class' => 'table table-striped data-table-net',
            //'extract_type' => 'object_property',
            'actions' => $actions,
            'search' => false,
            'columns' => array(
                'slug' => array(
                    'label' => $this->translate('Location')
                ),
                
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            )
        ));
        ?>
    </div>
</div>
<!-- Confirm Delete Many Modal -->
<div class="modal hide fade" role="dialog" id="confirm-delete-many">
    <div class="modal-header"> 
        <a class="close" data-dismiss="modal">&times;</a>
        <h3><?php echo $this->translate('Delete locations') ?></h3>
    </div>
    <div class="modal-body">
        <p id="count-locations"><?php echo $this->translate('You are about to delete "x" locations, this procedure is irreversible.') ?></p>
        <p><?php echo $this->translate('Do you want to proceed?') ?></p>        
    </div>
    <div class="modal-footer">
        <form method="post" action="
              <?php
                echo $this->application()->url(array('controller' => 'location',
                    'action' => 'delete-many',
                ));
              ?>
              ">
            <input name="delete_list" id="delete-list" type="hidden" value="">
            <button id="delete-many-btn" class="btn btn-danger" href="#"><?php echo $this->translate('Yes') ?></button> 
            <a class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate('No') ?></a>
        </form>     
    </div>
</div>