<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/group-actions.js', 'text/javascript');
?>
<div id="<?php echo $this->escapeHtml($this->id) ?>" class="modal hide fade confirm-modal" role="dialog">
    <div class="modal-header"> 
        <a class="close" data-dismiss="modal">&times;</a>
        <h3><?php echo $this->escapeHtml($this->title) ?></h3>
    </div>
    <div class="modal-body">
        <p class="modal-message"><?php echo $this->escapeHtml($this->message) ?></p>
    </div>
    <div class="modal-footer">
        <form method="post" action="<?php echo $this->application()->url($this->formAction) ?>">
            <input name="postCameFromList" type="hidden" />
            <?php
            if ($this->hiddenElements):
                foreach ($this->hiddenElements as $key => $value) :
                    ?>
                    <input name="<?php echo $this->escapeHtml($key) ?>" type="hidden" value="<?php echo $this->escapeHtml($value) ?>"/>
                <?php
                endforeach;
            endif;
            ?>
            <button class="btn btn-danger confirm-btn">
                <?php echo $this->translate('Continue') ?>
            </button>
            <a class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate('Cancel') ?></a>
        </form>     
    </div>
</div>