<?php 
$visualControlModalParams = array(
    'id' => 'confirm-visual-control-modal',
    'title' => $this->translate('Create visual controls'),
    'message' => $this->translate('You are creating visual control for 0 equipment instances...'),
    'formAction' => array(
        'controller' => 'visual-control',
        'action' => 'add'
    ),
    'hiddenElements' => array(
        'equipmentId' => $this->equipmentId,
    )
);
echo $this->partial('partial/groupActionConfirmModal.phtml', $visualControlModalParams);
?>