<?php
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$resetPasswordPath = $protocol. $_SERVER['SERVER_NAME'] . $this->basePath() . "/user/reset-password/key/" . $this->securityKey;
?>
Klikk på følgende link for å nullstille ditt passord og få oversendt nytt:<br><br>
<a href="<?php echo $resetPasswordPath ?>">Nullstill passord</a><br><br>
Med vennlig hilsen<br>
Support, Vidum Systems AS