<?php
echo $this->translate("You have been deactivated as a user of VEDOS MEDICAL.");
?>
<br />
<?php
echo $this->translate("If you need to be activated again take contact with:");
?>
<br />
Tor Lund                    <a href="mailto:tolund@mil.no">tolund@mil.no</a><br />
Magnus Meyer                <a href="mailto:magmeyer@mil.no">magmeyer@mil.no</a><br />
Øyvind Bekkeli              <a href="mailto:obekkeli@mil.no">obekkeli@mil.no</a><br />