<?php
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$loginPath = $protocol. $_SERVER['SERVER_NAME'] . $this->basePath() . "/user/login";
?>
Ditt passord er nullstilt.<br><br>
Ditt nye passord er: <strong><?php echo $this->newPassword ?></strong><br><br>
Logg inn her: <a href="<?php echo $loginPath ?>" />Logg inn</a><br><br>
Med vennlig hilsen<br>
Support, Vidum Systems AS