<div class="marketing">
    <img alt="Vidum logo" src="<?php echo $this->basePath(); ?>/images/vidum-logo-index.png">
</div>
<div class="page-header">
    <h2><?php echo $this->translate('Choose your application'); ?></h2>
</div>
<ul class="thumbnails">
    <?php foreach ($applications as $application): ?>
        <li class="span3">
            <a href="<?php echo $this->escapeHtml($this->url('base/wildcard', $application->getHome())); ?>">
                <div class="thumbnail">
                    <?php $appBackgroundImage = $this->basePath('/vidum-public/' . $this->escapeHtml($application->getDirectory()) . '/img/logo.png');?>
                    <div class="category-image" style="
                        background-image: url('<?php echo $appBackgroundImage ?>');
                        filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $appBackgroundImage ?>', sizingMethod='scale');
                    ">
                        <img src="<?php echo $this->basepath('/images/apps-thumbnail-placeholder.png'); ?>" alt="<?php echo $this->escapeHtml(ucfirst($application->getName())) ?>">
                    </div>
                </div>
            </a>
        </li>
    <?php endforeach; ?>
</ul>