CREATE TABLE user_competance_area_linker (user_id INT NOT NULL, competence_area_taxonomy_id INT NOT NULL, INDEX IDX_451C52C9A76ED395 (user_id), INDEX IDX_451C52C949C6FB23 (competence_area_taxonomy_id), PRIMARY KEY(user_id, competence_area_taxonomy_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE equipment_instance_history (equipment_instance_historical_id INT AUTO_INCREMENT NOT NULL, owner INT DEFAULT NULL, equipment_id INT DEFAULT NULL, location INT DEFAULT NULL, usage_status INT DEFAULT NULL, updated_by INT DEFAULT NULL, equipment_instance_id INT DEFAULT NULL, serial_number VARCHAR(50) NOT NULL, reg_number VARCHAR(50) DEFAULT NULL, batch_number VARCHAR(50) DEFAULT NULL, certificate_number VARCHAR(50) DEFAULT NULL, purchase_date DATETIME DEFAULT NULL, technical_lifetime DATETIME DEFAULT NULL, guarantee_time DATETIME DEFAULT NULL, reception_control DATETIME DEFAULT NULL, first_time_used DATETIME DEFAULT NULL, periodic_control_date DATETIME DEFAULT NULL, control_status VARCHAR(50) DEFAULT NULL, visual_control VARCHAR(1) DEFAULT NULL, order_number VARCHAR(100) DEFAULT NULL, rfid VARCHAR(100) DEFAULT NULL, remarks LONGTEXT DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, parent_id INT DEFAULT NULL, checked_out TINYINT(1) NOT NULL, date_updated DATETIME DEFAULT NULL, INDEX IDX_9533CC24CF60E67C (owner), INDEX IDX_9533CC24517FE9FE (equipment_id), INDEX IDX_9533CC245E9E89CB (location), INDEX IDX_9533CC24218F7464 (usage_status), INDEX IDX_9533CC2416FE72E1 (updated_by), INDEX IDX_9533CC245B13863A (equipment_instance_id), PRIMARY KEY(equipment_instance_historical_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE competence_area_taxonomy (competence_area_taxonomy_id INT AUTO_INCREMENT NOT NULL, type VARCHAR(45) DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, `order` INT DEFAULT NULL, `status` VARCHAR(20) DEFAULT NULL, application VARCHAR(255) NOT NULL, PRIMARY KEY(competence_area_taxonomy_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE visual_control (visual_control_id INT AUTO_INCREMENT NOT NULL, registered_by INT NOT NULL, control_status INT DEFAULT NULL, equipment_instance_id INT DEFAULT NULL, control_date DATETIME DEFAULT NULL, next_control_date DATETIME DEFAULT NULL, remarks LONGTEXT DEFAULT NULL, INDEX IDX_EE12F396B304A6FF (registered_by), INDEX IDX_EE12F3966E61B1FC (control_status), INDEX IDX_EE12F3965B13863A (equipment_instance_id), PRIMARY KEY(visual_control_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE user_competance_area_linker ADD CONSTRAINT FK_451C52C9A76ED395 FOREIGN KEY (user_id) REFERENCES user (user_id);
ALTER TABLE user_competance_area_linker ADD CONSTRAINT FK_451C52C949C6FB23 FOREIGN KEY (competence_area_taxonomy_id) REFERENCES competence_area_taxonomy (competence_area_taxonomy_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC24CF60E67C FOREIGN KEY (owner) REFERENCES organization (organization_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC24517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC245E9E89CB FOREIGN KEY (location) REFERENCES location_taxonomy (location_taxonomy_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC24218F7464 FOREIGN KEY (usage_status) REFERENCES equipment_instance_taxonomy (equipment_instance_taxonomy_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC2416FE72E1 FOREIGN KEY (updated_by) REFERENCES user (user_id);
ALTER TABLE equipment_instance_history ADD CONSTRAINT FK_9533CC245B13863A FOREIGN KEY (equipment_instance_id) REFERENCES equipment_instance (equipment_instance_id);
ALTER TABLE visual_control ADD CONSTRAINT FK_EE12F396B304A6FF FOREIGN KEY (registered_by) REFERENCES user (user_id);
ALTER TABLE visual_control ADD CONSTRAINT FK_EE12F3966E61B1FC FOREIGN KEY (control_status) REFERENCES periodic_control_taxonomy (periodic_control_taxonomy_id);
ALTER TABLE visual_control ADD CONSTRAINT FK_EE12F3965B13863A FOREIGN KEY (equipment_instance_id) REFERENCES equipment_instance (equipment_instance_id);
ALTER TABLE organization ADD application VARCHAR(255) NOT NULL;
ALTER TABLE location_taxonomy ADD application VARCHAR(255) NOT NULL;
ALTER TABLE attachment_taxonomy ADD application VARCHAR(255) NOT NULL;
ALTER TABLE periodic_control_taxonomy ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipmentmeta ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_taxonomy ADD competence_area_taxonomy_id INT DEFAULT NULL, ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_taxonomy ADD CONSTRAINT FK_CDD13C1B49C6FB23 FOREIGN KEY (competence_area_taxonomy_id) REFERENCES competence_area_taxonomy (competence_area_taxonomy_id);
CREATE INDEX IDX_CDD13C1B49C6FB23 ON equipment_taxonomy (competence_area_taxonomy_id);
ALTER TABLE equipment_instance ADD updated_by INT DEFAULT NULL, ADD rfid VARCHAR(100) DEFAULT NULL, ADD date_updated DATETIME DEFAULT NULL;
ALTER TABLE equipment_instance ADD CONSTRAINT FK_72F335F816FE72E1 FOREIGN KEY (updated_by) REFERENCES user (user_id);
CREATE INDEX IDX_72F335F816FE72E1 ON equipment_instance (updated_by);
ALTER TABLE equipment_instance_taxonomy ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE page ADD application VARCHAR(255) NOT NULL;
ALTER TABLE question_option CHANGE option_text option_text VARCHAR(500) DEFAULT NULL;
ALTER TABLE question ADD order_number INT DEFAULT NULL;
ALTER TABLE best_practice_attachment_taxonomy ADD application VARCHAR(255) NOT NULL;