CREATE TABLE best_practice_attachment_taxonomy (attachment_taxonomy_id INT AUTO_INCREMENT NOT NULL, type VARCHAR(45) DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, `order` INT DEFAULT NULL, `status` VARCHAR(20) DEFAULT NULL, PRIMARY KEY(attachment_taxonomy_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE best_practice (best_practice_id INT AUTO_INCREMENT NOT NULL, equipment_id INT NOT NULL, title VARCHAR(100) NOT NULL, subtitle VARCHAR(100) DEFAULT NULL, featured_image VARCHAR(100) DEFAULT NULL, slides LONGTEXT DEFAULT NULL COMMENT '(DC2Type:simple_array)', version_id INT DEFAULT NULL, identifier VARCHAR(50) DEFAULT NULL, revision_date DATETIME DEFAULT NULL, revision_number VARCHAR(50) NOT NULL, comment LONGTEXT DEFAULT NULL, INDEX IDX_FE6D461F517FE9FE (equipment_id), PRIMARY KEY(best_practice_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE best_practice_attachment (attachment_id INT AUTO_INCREMENT NOT NULL, best_practice_id INT DEFAULT NULL, attachment_taxonomy_id INT DEFAULT NULL, title VARCHAR(200) DEFAULT NULL, description LONGTEXT DEFAULT NULL, file VARCHAR(200) DEFAULT NULL, author VARCHAR(200) DEFAULT NULL, version VARCHAR(100) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, date_add DATETIME DEFAULT NULL, INDEX IDX_F3730EA2E41BD4E5 (best_practice_id), INDEX IDX_F3730EA2AE9BD797 (attachment_taxonomy_id), PRIMARY KEY(attachment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE subscription (subscription_id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, identifier VARCHAR(50) NOT NULL, pending_notification_id INT NOT NULL, INDEX IDX_A3C664D3A76ED395 (user_id), PRIMARY KEY(subscription_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE best_practice ADD CONSTRAINT FK_FE6D461F517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id);
ALTER TABLE best_practice_attachment ADD CONSTRAINT FK_F3730EA2E41BD4E5 FOREIGN KEY (best_practice_id) REFERENCES best_practice (best_practice_id);
ALTER TABLE best_practice_attachment ADD CONSTRAINT FK_F3730EA2AE9BD797 FOREIGN KEY (attachment_taxonomy_id) REFERENCES attachment_taxonomy (attachment_taxonomy_id);
ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES user (user_id);

insert into `best_practice_attachment_taxonomy` (`type`, `name`, `slug`, `description`, `order`, `status`) values('user-manual','User manual','user-manual',NULL,NULL,'active');
insert into `best_practice_attachment_taxonomy` (`type`, `name`, `slug`, `description`, `order`, `status`) values('procedures','Procedures','procedures',NULL,NULL,'active');
insert into `best_practice_attachment_taxonomy` (`type`, `name`, `slug`, `description`, `order`, `status`) values('additional-info','Additional info','additional-info',NULL,NULL,'active');
