CREATE TABLE application (application_id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(application_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE user_application_linker (user_id INT NOT NULL, application_id INT NOT NULL, INDEX IDX_7F5BBA83A76ED395 (user_id), INDEX IDX_7F5BBA833E030ACD (application_id), PRIMARY KEY(user_id, application_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE user_application_linker ADD CONSTRAINT FK_7F5BBA83A76ED395 FOREIGN KEY (user_id) REFERENCES user (user_id);
ALTER TABLE user_application_linker ADD CONSTRAINT FK_7F5BBA833E030ACD FOREIGN KEY (application_id) REFERENCES application (application_id);
ALTER TABLE attachment_taxonomy DROP application;
ALTER TABLE organization DROP application;
ALTER TABLE competence_area_taxonomy DROP application;
ALTER TABLE equipment_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_instance ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_instance_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_instance_taxonomy DROP application;
ALTER TABLE periodic_control DROP FOREIGN KEY FK_CE65323D5B13863A;
ALTER TABLE periodic_control ADD application VARCHAR(255) NOT NULL;
ALTER TABLE periodic_control ADD CONSTRAINT FK_CE65323D5B13863A FOREIGN KEY (equipment_instance_id) REFERENCES equipment_instance (equipment_instance_id) ON DELETE CASCADE;
ALTER TABLE periodic_controls_control_point_results DROP FOREIGN KEY FK_A310F1909A5A729B;
ALTER TABLE periodic_controls_control_point_results ADD CONSTRAINT FK_A310F1909A5A729B FOREIGN KEY (periodic_control_id) REFERENCES periodic_control (periodic_control_id) ON DELETE CASCADE;
ALTER TABLE periodic_control_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE periodic_control_taxonomy DROP application;
ALTER TABLE visual_control DROP FOREIGN KEY FK_EE12F3965B13863A;
ALTER TABLE visual_control ADD application VARCHAR(255) NOT NULL;
ALTER TABLE visual_control ADD CONSTRAINT FK_EE12F3965B13863A FOREIGN KEY (equipment_instance_id) REFERENCES equipment_instance (equipment_instance_id) ON DELETE CASCADE;
ALTER TABLE training_section ADD application VARCHAR(255) NOT NULL;
ALTER TABLE training_section_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE documentation_section ADD application VARCHAR(255) NOT NULL;
ALTER TABLE documentation_section_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE inline_section ADD application VARCHAR(255) NOT NULL;
ALTER TABLE inline_section_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE page_inline_section ADD application VARCHAR(255) NOT NULL;
ALTER TABLE page_inline_section_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE page_section ADD application VARCHAR(255) NOT NULL;
ALTER TABLE page_section_attachment ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_certification ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_exam ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_exam_attempt ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_exercise ADD application VARCHAR(255) NOT NULL;
ALTER TABLE equipment_exercise_attempt ADD application VARCHAR(255) NOT NULL;
ALTER TABLE question ADD application VARCHAR(255) NOT NULL;
ALTER TABLE best_practice_attachment_taxonomy DROP application;
ALTER TABLE best_practice ADD application VARCHAR(255) NOT NULL;
ALTER TABLE best_practice_attachment ADD application VARCHAR(255) NOT NULL;