<?php
$this->headTitle($title);
$this->layout()->title = $title;
$this->inlineScript()->appendFile($this->basePath() . '/js/certification/certification.js', 'text/javascript');

$actionsArray = array();
$certificationResource = 'Certification\Entity\Certification';

if ($this->isAllowed($certificationResource, 'create')) {
    $actionsArray['add'] = array(
        'label' => $this->translate('Add new'),
        'attributes' => array(
            'href' => $this->application()->url(array(
                'controller' => 'certification',
                'action' => 'add',
                'id' => $this->equipmentId))
        )
    );
}
$actionsArray['options'] = array();
if ($this->isAllowed($certificationResource, 'update')) {
    $actionsArray['options']['edit'] = true;
}
if ($this->isAllowed($certificationResource, 'delete')) {
    $actionsArray['group'] = array('delete-selected' => true);
    $actionsArray['options']['delete'] = true;
}
?>

<!-- Alert -->
<div class="delete-alert alert fade in">
    <button type="button" class="close">&times;</button>    
    <strong><?php echo $this->translate('You must select a certification') ?></strong>
</div>

<div class="row">    
    <div class="span12">
        <?php
        echo $this->bootstrapDataTable($this->certifications, array(
            'object_id' => 'certificationId',
            'actions' => $actionsArray,
            'table_class' => 'table table-striped data-table-net',
            'search' => false,
            'columns' => array(
                'user' => array(
                    'label' => $this->translate('User'),
                    'callback' => function($user, $view) {                        
                        $href = $view->application()->url(array(
                                'controller' => 'certification',
                                'action' => 'user',
                                'id' => $user->getId()));
                        return '<a href="' . $href . '">' . $user . '</a>';
                    }
                ),
                'userOrganization' => array(
                    'label' => $this->translate('Organization'),
                ),
                'theoryPassed' => array(
                    'label' => $this->translate('Theory exam'),
                    'callback' => 'isPassed'
                ),
                'practicalPassed' => array(
                    'label' => $this->translate('Practical exam'),
                    'callback' => 'isPassed'      
                ),
                'valid' => array(
                    'label' => $this->translate('Certified'),
                    'callback' => 'isPassed'
                ),
                'expirationDate' => array(
                    'label' => $this->translate('Expires'),
                    'callback' => function($date, $view) {
                        $output = $view->dateFormat($date, IntlDateFormatter::SHORT);
                        if($view->application()->isDateExpired($date))
                            $output = "<span class='red'>" . $output . "</span>";
                        return $output;
                    }
                ),
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            )
        ));
        ?>
    </div>
</div>

<!-- Delete many Modal -->
<?php
$deleteManyModalParams = array(
    'id' => 'confirm-delete-modal',
    'title' => $this->translate('Delete Certifications'),
    'message' => $this->translate('You are about to delete 0 certifications, this procedure is irreversible.'),
    'formAction' => array(
        'controller' => 'certification',
        'action' => 'delete-many'
    ),
    'hiddenElements' => array(
        'equipmentId' => $this->equipmentId
    )
);
echo $this->partial('partial/groupActionConfirmModal.phtml', $deleteManyModalParams);


function isPassed($passed) 
{
    return ($passed) ? '<i class="icon-ok"></i>' : '';
}