<?php
if(isset($form)) {
   
    $title = $this->translate('Mass update of instances');
    $this->layout()->title = $title;
    $this->headTitle($title);
    $this->inlineScript()->appendFile($this->basePath() . '/js/equipment/equipment-instance.js', 'text/javascript');
    $form->setAttribute('action',$this->application()->url(array('controller' => 'equipment-instance',
            'action' => 'update-many',
            'id'=> $equipment->getEquipmentId()
        )));
    echo $this->bootstrapForm($form);
}
?>
<div id="control-interval-container">
    <span id="control-interval-for-equipment">
        <?php echo $this->escapeHtml($this->equipment->getControlIntervalByDays()) ?>
    </span>
</div>
<?php $this->partial('partial/set-control-date-js.phtml', array('controlInterval' => $this->equipment->getControlIntervalByDays()));

