<?php
$this->headTitle($title);
$this->layout()->title = $title;

$organizationResource = 'Application\Entity\Organization';
$canCreateOrganization = $this->isAllowed($organizationResource, 'create');
$canUpdateOrganization = $this->isAllowed($organizationResource, 'update');
$canDeleteOrganization = $this->isAllowed($organizationResource, 'delete');

$actions = array();
$options = array();
if($canCreateOrganization)
    $actions['add'] = true;
if($canUpdateOrganization)
    $options['edit'] = true;
if($canDeleteOrganization) {
    $options['deactivate'] = array(
        'label' => $this->translate("Deactivate"),
        'icon' => 'off',
        'attributes' => array(
            'href' => $this->application()->url(
                array(
                    'controller' => 'organization',
                    'action' => 'deactivate',
                    'id' => ":organizationId",
                )
            ),
            'class' => 'deactivateButton'
        ),
    );
    $options['activate'] = array(
        'label' => $this->translate("Activate"),
        'icon' => 'off',
        'attributes' => array(
            'href' => $this->application()->url(
                array(
                    'controller' => 'organization',
                    'action' => 'activate',
                    'id' => ":organizationId",
                )
            ),
            'class' => 'activateButton',
        ),
    );
    $actions['group'] = array('deactivate-all' =>
        array(
            'attributes' => array(
                'id' => 'organization-deactivate-all',
                'href' => '#',
            ),
            'label' => $this->translate('Deactivate')
        )
    );
}
$actions['options'] = $options;

?>

<!-- Alert -->
<div class="delete-alert alert fade in">
    <button type="button" class="close">&times;</button>
    <strong><?php echo $this->translate('You must select an Organization') ?></strong>
</div>


<div class="row row-desktop">
    <div class="span3">
        <?php echo $this->partial('partial/admin-menu.phtml', 'application') ?>
    </div>
    <div class="span9">
        <?php
        echo $this->bootstrapDataTable($this->organizations, array(
            'object_id' => 'organizationId',
            'actions' => $actions,
            'table_class' => 'table table-striped data-table-net',
            'table_row_class' => function ($item) {
                if ($item->getStatus() === 'active') {
                    return 'status-active';
                } else {
                    return 'status-inactive';
                }
            },
            'search' => false,
            'columns' => array(
                'name' => array(
                    'label' => $this->translate('Organization')
                ),
                'typeReadable' => array(
                    'label' => $this->translate('Type'),
                    'callback' => function($item, $view) {
                        return $view->translate($item);
                    }
                ),
                'email' => array(
                    'label' => $this->translate('Email')
                ),
                'phone' => array(
                    'label' => $this->translate('Phone Number')
                ),
                'status' => array(
                    'label' => $this->translate('Status'),
                    'class' => 'status-column',
                    'callback' => function ($output, $view) {
                        $output = trim(strtolower($output));
                        if ($output === 'active') {
                            return $view->translate("Active");
                        } else if ($output === 'inactive') {
                            return $view->translate("Inactive");
                        }
                        return $output;
                    },
                )
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            ),
        ));
        ?>
    </div>
</div>
<!-- Confirm Delete Many Modal -->
<div class="modal hide fade" role="dialog" id="confirm-delete-many">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>

        <h3><?php echo $this->translate('Deactivate Organizations') ?></h3>
    </div>
    <div class="modal-body">
        <p id="count-organizations"><?php echo $this->translate('You are about to deactivate "x" organizations.') ?></p>

        <p><?php echo $this->translate('Do you want to proceed?') ?></p>
    </div>
    <div class="modal-footer">
        <form method="post" action="<?php
        echo $this->application()->url(array('action' => 'deactivate-many',
            'controller' => 'organization')); ?>">
            <input name="deactivate_ids" id="deactivate-ids" type="hidden" value="">
            <button id="delete-many-btn" class="btn btn-danger" href="#"><?php echo $this->translate('Yes') ?></button>
            <a class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate('No') ?></a>
        </form>
    </div>
</div>


<?php
$this->inlineScript()->appendFile($this->basePath() . '/js/organization.js', 'text/javascript');
$this->inlineScript()->appendFile($this->basePath() . '/js/application/deactivate-table-buttons.js', 'text/javascript');
$this->inlineScript()->appendFile($this->basePath() . '/js/application/datatable-active-filter.js', 'text/javascript');
?>
