<?php
$this->headTitle($this->title);
$this->layout()->title = $this->title;

?>

<!-- Alert -->
<div class="delete-alert alert fade in">
    <button type="button" class="close">&times;</button>
    <strong><?php echo $this->translate('You must select a category') ?></strong>
</div>


<div class="row row-desktop">
    <div class="span3">
        <?php echo $this->partial('partial/admin-menu.phtml', 'application') ?>
    </div>
    <div class="span9">
        <?php
        echo $this->bootstrapDataTable($this->categories, array(
            'object_id' => 'equipmentTaxonomyId',
            'actions' => array(
                'add' => true,
                'options' => array(
                    'edit' => true,
                    'deactivate' => array(
                        'label' => $this->translate("Deactivate"),
                        'icon' => 'off',
                        'attributes' => array(
                            'href' => '#:equipmentTaxonomyId',
                            'class' => 'deactivateButton',
                        ),
                    ),
                    'activate' => array(
                        'label' => $this->translate("Activate"),
                        'icon' => 'off',
                        'attributes' => array(
                            'href' => '#:equipmentTaxonomyId',
                            'class' => 'activateButton'
                        ),
                    ),
                ),
                'group' => array(
                    'deactivate-all' => array(
                        'attributes' => array(
                            'id' => 'deactivate-many-button',
                            'href' => '#',
                        ),
                        'label' => $this->translate('Deactivate')
                    ),
                ),
            ),
            'table_class' => 'table table-striped data-table-net',
            'table_row_class' => function ($item) {
                if ($item->getStatus() === 'active') {
                    return 'status-active';
                } else {
                    return 'status-inactive';
                }
            },
            'search' => false,
            'columns' => array(
                'name' => array(
                    'label' => $this->translate('Name')
                ),
                'parent' => array(
                    'label' => $this->translate('Parent category')
                ),
                'status' => array(
                    'label' => $this->translate('Status'),
                    'callback' => function ($output, $view) {
                        $output = trim(strtolower($output));
                        if ($output === 'active') {
                            return $view->translate("Active");
                        } else if ($output === 'inactive') {
                            return $view->translate("Inactive");
                        }
                        return $output;
                    },
                )
            ),
            'params' => array(
                'basic' => array('application', 'controller', 'action')
            ),
        ));
        ?>
    </div>
</div>

<?php
echo $this->partial('partial/submit-modal.phtml', array(
    'controller' => 'equipment-taxonomy',
    'action' => 'deactivate-many',
    'title' => $this->translate('Deactivate categories'),
    'message' => $this->translate('You are about to deactivate several categories.')
));

echo $this->partial('partial/submit-modal.phtml', array(
    'controller' => 'equipment-taxonomy',
    'action' => 'deactivate',
    'title' => $this->translate('Deactivate category'),
    'message' => $this->translate('You are about to deactivate a category.')
));

echo $this->partial('partial/submit-modal.phtml', array(
    'controller' => 'equipment-taxonomy',
    'action' => 'reactivate',
    'title' => $this->translate('Reactivate category'),
    'message' => $this->translate('You are about to reactivate a category.')
));


$this->inlineScript()->appendFile($this->basePath() . '/js/equipment/equipment-taxonomy/admin-index.js', 'text/javascript');
$this->inlineScript()->appendFile($this->basePath() . '/js/application/deactivate-table-buttons.js', 'text/javascript');
$this->inlineScript()->appendFile($this->basePath() . '/js/application/datatable-active-filter.js', 'text/javascript');

?>