<div class="container inner-wrapper">
    <div class="marketing">
        <img alt="Vidum logo" src="<?php echo $this->basePath(); ?>/images/vidum-logo-login.png">
    </div>
    <hr>
    <div class="text-center">
        <?php
        $form = $this->loginForm;
        $form->prepare();
        $form
                ->setAttribute('action', $this->url('zfcuser/login'))
                ->setAttribute('method', 'post')
                ->setAttribute('id', 'form-login')
                ->setAttribute('class', 'form-inline');
        ?>
        <?php echo $this->form()->openTag($form) ?>
        <?php if ($form->getMessages()): ?>
            <div class="alert alert-error alert-block">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?php echo implode('<br/>', current($form->getMessages())); ?>
            </div>
        <?php endif; ?>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <label for="identity"><?php echo $this->translate('E-mail or username') ?></label>
        <label for="credential" class="last-label"><?php echo $this->translate('Password') ?></label>
        <?php echo $this->formElement($form->get('identity')->setAttribute('placeholder', $this->translate('E-mail or username'))->setAttribute('required', true)) ?>
        <?php echo $this->formInput($form->get('credential')->setAttribute('placeholder', $this->translate('Password'))->setAttribute('required', true)); ?>
        <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
        <?php echo $this->form()->closeTag() ?>

    </div>
    <div id="forgot-password">
        <a class="pull-left" href="<?php echo $this->basePath('/user/forgot-password') ?>" >
            <small><?php echo $this->translate('Forgot password'); ?>?</small></a>
    </div>
</div>