<?php

namespace DoctrineORMModule\Proxy\__CG__\Equipment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ControlPoint extends \Equipment\Entity\ControlPoint implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'controlPointId', 'label', 'controlPointOptionCollection', 'controlPointToTemplate'];
        }

        return ['__isInitialized__', 'controlPointId', 'label', 'controlPointOptionCollection', 'controlPointToTemplate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ControlPoint $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getControlPointId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getControlPointId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControlPointId', []);

        return parent::getControlPointId();
    }

    /**
     * {@inheritDoc}
     */
    public function setControlPointId($controlPointId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setControlPointId', [$controlPointId]);

        return parent::setControlPointId($controlPointId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getControlPointOptionCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControlPointOptionCollection', []);

        return parent::getControlPointOptionCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getControlPointOptionsAsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControlPointOptionsAsArray', []);

        return parent::getControlPointOptionsAsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setControlPointOptionCollection($controlPointOptionCollection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setControlPointOptionCollection', [$controlPointOptionCollection]);

        return parent::setControlPointOptionCollection($controlPointOptionCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function addControlPointOptionCollection(\Doctrine\Common\Collections\ArrayCollection $controlPointOptionCollection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addControlPointOptionCollection', [$controlPointOptionCollection]);

        return parent::addControlPointOptionCollection($controlPointOptionCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function removeControlPointOptionCollection(\Doctrine\Common\Collections\ArrayCollection $controlPointOptionCollection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeControlPointOptionCollection', [$controlPointOptionCollection]);

        return parent::removeControlPointOptionCollection($controlPointOptionCollection);
    }

    /**
     * {@inheritDoc}
     */
    public function getControlPointToTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControlPointToTemplate', []);

        return parent::getControlPointToTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setControlPointToTemplate(\Equipment\Entity\ControlPointToTemplate $controlPointToTemplate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setControlPointToTemplate', [$controlPointToTemplate]);

        return parent::setControlPointToTemplate($controlPointToTemplate);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$name, $arguments]);

        return parent::__call($name, $arguments);
    }

}
